language: node_js
jobs:
  include:
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
    - stage: test
      node_js:
        - 12.11.1
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
